apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workpro-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts: [app.example.com, api.example.com]
      secretName: workpro-prod-tls
