apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
  - namespace.yaml
namespace: workpro-prod
patches:
  - path: patch-ingress.yaml
  - path: patch-configmap.yaml
  - path: patch-certificate.yaml
images:
  - name: workpro-backend
    digest: sha256:1111111111111111111111111111111111111111111111111111111111111111
  - name: workpro-frontend
    digest: sha256:2222222222222222222222222222222222222222222222222222222222222222
