apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: workpro-prod
resources:
  - ../../
patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml
configMapGenerator:
  - name: workpro-config
    literals:
      - NODE_ENV=production
      - CORS_ORIGIN=https://app.example.com
