apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workpro-ingress
spec:
  tls:
    - hosts:
        - workpro.example.com
      secretName: workpro-prod-tls
  rules:
    - host: workpro.example.com
