apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workpro-backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: workpro-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: workpro-frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: workpro-frontend
