apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: workpro-tls
spec:
  secretName: workpro-tls
  dnsNames:
    - workpro.example
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
