apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workpro-app-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: workpro-secret-store
    kind: ClusterSecretStore
  target:
    name: workpro-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: workpro/prod/jwt-secret
    - secretKey: MONGO_URI
      remoteRef:
        key: workpro/prod/mongo-uri
