apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: workpro-ingress
spec:
  tls:
    - hosts:
        - workpro.local
      secretName: workpro-dev-tls
  rules:
    - host: workpro.local
